# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gekimaru/projekt/Jaskinia_procesy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gekimaru/projekt/Jaskinia_procesy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gekimaru/projekt/Jaskinia_procesy/CMakeFiles /home/gekimaru/projekt/Jaskinia_procesy//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gekimaru/projekt/Jaskinia_procesy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named kasjer

# Build rule for target.
kasjer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kasjer
.PHONY : kasjer

# fast build rule for target.
kasjer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kasjer.dir/build.make CMakeFiles/kasjer.dir/build
.PHONY : kasjer/fast

#=============================================================================
# Target rules for targets named zwiedzajacy

# Build rule for target.
zwiedzajacy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zwiedzajacy
.PHONY : zwiedzajacy

# fast build rule for target.
zwiedzajacy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zwiedzajacy.dir/build.make CMakeFiles/zwiedzajacy.dir/build
.PHONY : zwiedzajacy/fast

#=============================================================================
# Target rules for targets named przewodnik

# Build rule for target.
przewodnik: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 przewodnik
.PHONY : przewodnik

# fast build rule for target.
przewodnik/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/przewodnik.dir/build.make CMakeFiles/przewodnik.dir/build
.PHONY : przewodnik/fast

#=============================================================================
# Target rules for targets named straznik

# Build rule for target.
straznik: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 straznik
.PHONY : straznik

# fast build rule for target.
straznik/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/straznik.dir/build.make CMakeFiles/straznik.dir/build
.PHONY : straznik/fast

kasjer.o: kasjer.cpp.o
.PHONY : kasjer.o

# target to build an object file
kasjer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kasjer.dir/build.make CMakeFiles/kasjer.dir/kasjer.cpp.o
.PHONY : kasjer.cpp.o

kasjer.i: kasjer.cpp.i
.PHONY : kasjer.i

# target to preprocess a source file
kasjer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kasjer.dir/build.make CMakeFiles/kasjer.dir/kasjer.cpp.i
.PHONY : kasjer.cpp.i

kasjer.s: kasjer.cpp.s
.PHONY : kasjer.s

# target to generate assembly for a file
kasjer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kasjer.dir/build.make CMakeFiles/kasjer.dir/kasjer.cpp.s
.PHONY : kasjer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

przewodnik.o: przewodnik.cpp.o
.PHONY : przewodnik.o

# target to build an object file
przewodnik.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/przewodnik.dir/build.make CMakeFiles/przewodnik.dir/przewodnik.cpp.o
.PHONY : przewodnik.cpp.o

przewodnik.i: przewodnik.cpp.i
.PHONY : przewodnik.i

# target to preprocess a source file
przewodnik.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/przewodnik.dir/build.make CMakeFiles/przewodnik.dir/przewodnik.cpp.i
.PHONY : przewodnik.cpp.i

przewodnik.s: przewodnik.cpp.s
.PHONY : przewodnik.s

# target to generate assembly for a file
przewodnik.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/przewodnik.dir/build.make CMakeFiles/przewodnik.dir/przewodnik.cpp.s
.PHONY : przewodnik.cpp.s

straznik.o: straznik.cpp.o
.PHONY : straznik.o

# target to build an object file
straznik.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/straznik.dir/build.make CMakeFiles/straznik.dir/straznik.cpp.o
.PHONY : straznik.cpp.o

straznik.i: straznik.cpp.i
.PHONY : straznik.i

# target to preprocess a source file
straznik.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/straznik.dir/build.make CMakeFiles/straznik.dir/straznik.cpp.i
.PHONY : straznik.cpp.i

straznik.s: straznik.cpp.s
.PHONY : straznik.s

# target to generate assembly for a file
straznik.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/straznik.dir/build.make CMakeFiles/straznik.dir/straznik.cpp.s
.PHONY : straznik.cpp.s

zwiedzajacy.o: zwiedzajacy.cpp.o
.PHONY : zwiedzajacy.o

# target to build an object file
zwiedzajacy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zwiedzajacy.dir/build.make CMakeFiles/zwiedzajacy.dir/zwiedzajacy.cpp.o
.PHONY : zwiedzajacy.cpp.o

zwiedzajacy.i: zwiedzajacy.cpp.i
.PHONY : zwiedzajacy.i

# target to preprocess a source file
zwiedzajacy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zwiedzajacy.dir/build.make CMakeFiles/zwiedzajacy.dir/zwiedzajacy.cpp.i
.PHONY : zwiedzajacy.cpp.i

zwiedzajacy.s: zwiedzajacy.cpp.s
.PHONY : zwiedzajacy.s

# target to generate assembly for a file
zwiedzajacy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zwiedzajacy.dir/build.make CMakeFiles/zwiedzajacy.dir/zwiedzajacy.cpp.s
.PHONY : zwiedzajacy.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... kasjer"
	@echo "... main"
	@echo "... przewodnik"
	@echo "... straznik"
	@echo "... zwiedzajacy"
	@echo "... kasjer.o"
	@echo "... kasjer.i"
	@echo "... kasjer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... przewodnik.o"
	@echo "... przewodnik.i"
	@echo "... przewodnik.s"
	@echo "... straznik.o"
	@echo "... straznik.i"
	@echo "... straznik.s"
	@echo "... zwiedzajacy.o"
	@echo "... zwiedzajacy.i"
	@echo "... zwiedzajacy.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

